services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ../backend/.env
    ports:
      - "5432:5432"
    networks:
      - web
    volumes:
      - ../backend/db/data:/var/lib/postgresql/data

  backend:
    image: node:22.4.0
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - web
    working_dir: /usr/src/app
    volumes:
      - ../backend:/usr/src/app
      - ../backend/.yarnrc.yml:/usr/src/app/.yarnrc.yml
      - ../backend/.yarn:/usr/src/app/.yarn
    env_file:
      - ../backend/.env
    command: bash -c "
      yarn install
      && yarn start:dev"

  frontend:
    image: node:22.4.0
    restart: always
    depends_on:
      - backend
    networks:
      - web
    working_dir: /usr/src/app
    volumes:
      - ../frontend:/usr/src/app
      - ../frontend/.yarnrc.yml:/usr/src/app/.yarnrc.yml
      - ../frontend/.yarn:/usr/src/app/.yarn
    env_file:
      - ../backend/.env
    command: bash -c "
      yarn install
      && yarn dev --host 0.0.0.0"

  nginx:
    build: nginx
    depends_on:
      - frontend
      - backend
      - postgres
    restart: always
    ports:
      - "80:80"
    networks:
      - web
    volumes:
      - ./nginx-dev/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-dev/nginx.conf:/etc/nginx/nginx.conf:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

networks:
  web:

