services:
  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - ../backend/.env.prod
    networks:
      - web
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    image: node:22.4.0
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ../backend/.env.prod
    depends_on:
      - mongo
    networks:
      - web
    working_dir: /usr/src/app
    volumes:
      - ../backend:/usr/src/app
    command: bash -c "
      npm install
      && npm run dev"

  frontend:
    image: node:22.4.0
    restart: always
    depends_on:
      - backend
    networks:
      - web
    working_dir: /usr/src/app
    volumes:
      - ../frontend:/usr/src/app
    ports:
      - "5050:5050"
    command: bash -c "
      npm install
      && npm run dev"

  nginx:
    build: nginx
    depends_on:
      - frontend
      - backend
      - mongo
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend-build:/usr/share/nginx/html
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


networks:
  web:

volumes:
  frontend-build:
  mongo-data:
